// AUTO-GENERATED by `python -m data_gen.build`. Do not edit by hand.
import type { Scenario } from '../types'
import filamentScrewStarvation from './filament-screw-starvation.json'
import pipeDiameterDriftDemo from './pipe-diameter-drift-demo.json'

export const scenarios: Scenario[] = [
  filamentScrewStarvation as Scenario,
  pipeDiameterDriftDemo as Scenario,
]

export const activeScenario: Scenario = scenarios[0]
