"""JSON output and src/data/scenarios/index.ts regeneration."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


def write_scenario_json(out_dir: Path, scenario: dict[str, Any]) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{scenario['id']}.json"
    text = json.dumps(scenario, indent=2, ensure_ascii=False, sort_keys=False)
    path.write_text(text + "\n", encoding="utf-8")
    return path


def _to_camel(filename_stem: str) -> str:
    parts = re.split(r"[-_]", filename_stem)
    if not parts:
        return filename_stem
    head, *tail = [p for p in parts if p]
    return head + "".join(word[:1].upper() + word[1:] for word in tail)


def write_index_ts(out_dir: Path) -> Path:
    json_files = sorted(out_dir.glob("*.json"))
    if not json_files:
        raise RuntimeError(f"no JSON scenarios found in {out_dir}")

    imports: list[str] = []
    array_entries: list[str] = []
    for path in json_files:
        ident = _to_camel(path.stem)
        imports.append(f"import {ident} from './{path.name}'")
        array_entries.append(f"  {ident} as Scenario,")

    lines = [
        "// AUTO-GENERATED by `python -m data_gen.build`. Do not edit by hand.",
        "import type { Scenario } from '../types'",
        *imports,
        "",
        "export const scenarios: Scenario[] = [",
        *array_entries,
        "]",
        "",
        "export const activeScenario: Scenario = scenarios[0]",
        "",
    ]

    path = out_dir / "index.ts"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
